### ISSUE TITLE
Strange HouseSDJpaService behavior

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#123]
## 🐛 Describe the bug

In HouseSDJpaService I found a few things that seemed strange to me:

## ⚠️ Current behavior

First: `addHouseMembers` - Is it necessary to save empty `HouseMemberDocument`? I mean it works well without this `for` loop.
```
@Override public Set<HouseMember> addHouseMembers(String houseId, Set<HouseMember> houseMembers) {
    CommunityHouse communityHouse = communityHouseRepository.findByHouseId(houseId);
    Set<HouseMember> savedMembers = new HashSet<>();
    if (communityHouse != null) {
      for (HouseMember member : houseMembers) {
        HouseMemberDocument document = new HouseMemberDocument();
        member.setHouseMemberDocument(document);
        houseMemberDocumentRepository.save(document);
      }
      houseMembers.forEach(member -> member.setMemberId(generateUniqueId()));
      houseMembers.forEach(member -> member.setCommunityHouse(communityHouse));
      houseMemberRepository.saveAll(houseMembers).forEach(savedMembers::add);

      communityHouse.getHouseMembers().addAll(savedMembers);
      communityHouseRepository.save(communityHouse);
    }
    return savedMembers;
  }
```
Second: `deleteMemberFromHouse` - this method remove `HouseMember` from `CommunityHouse` but it not delete `HouseMember` entity in database. In app no controller for `HouseMember` so after remove `HouseMember` from `CommunityHouse` we can't access it (and its `HouseMemberDocument`) from app
```
@Override
  public boolean deleteMemberFromHouse(String houseId, String memberId) {
    CommunityHouse communityHouse = communityHouseRepository.findByHouseId(houseId);
    boolean isMemberRemoved = false;
    if (communityHouse != null && !CollectionUtils.isEmpty(communityHouse.getHouseMembers())) {
      Set<HouseMember> houseMembers = communityHouse.getHouseMembers();
      for (HouseMember member : houseMembers) {
        if (member.getMemberId().equals(memberId)) {
          houseMembers.remove(member);
          communityHouse.setHouseMembers(houseMembers);
          communityHouseRepository.save(communityHouse);
          member.setCommunityHouse(null);
          houseMemberRepository.save(member);
          isMemberRemoved = true;
          break;
        }
      }
    }
    return isMemberRemoved;
  }
```
Third - can we return `Optional<CommunityHouse>` from `communityHouseRepository.findByHouseId(houseId)`?
```
@Override
  public Optional<CommunityHouse> getHouseDetailsById(String houseId) {
    return Optional.ofNullable(communityHouseRepository.findByHouseId(houseId));
  }
```
## ✅ Expected behavior

* remove `for` loop from `addHouseMembers` method
* delete `HouseMember` entity after it was removed from `CommunityHouse`
* make some refactor `HouseSDJpaService` and `CommunityHouseRepository`

**Comment by edwardUL99** [comment]
@DDmit04 I think you can safely remove the for loop. If I remember correctly I added it because when I developed it, I had a set of payments in the HouseMember entity and when scheduling payments I would add the payment to this set so that when getting payments for a member endpoint would be called, it can use this set. After I added a payment to this set I would save the house member back into the database. But this would cause weird exceptions like a transient unsaved entity if they had a null HouseMemberDocument or a document that wasn't saved to the HouseMemberDocumentRepository.  So to fix this I added an empty HouseMemberDocument to save for that HouseMember. But I changed the implementation to retrieve payments directly from the PaymentsRepository for that member, so I no longer required this and it slipped my mind to remove it. Sorry for any confusion!

**Comment by DDmit04** [comment]
So what about `HouseMember` deleteion? If `HouseMember` was removed from `CommunityHouse` should we just delete it from database?
