### ISSUE TITLE
UserController - id with String type

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#73]
## 🐛 Describe the bug
In `UserController` there is a `getUserDetails(String userId)` method that has id as a String type.
This can allow to pass a non-numeric value to API call.

## ⚠️ Current behavior

`String userId`

## ✅ Expected behavior

`Integer userId`

## 📱 Tech info

- Device: All
- OS: All
- Library/App version: Java8

**Comment by Tobi406** [comment]
The userId is an UUID so I don't think Integer is the correct type for that

**Comment by mslowiak** [comment]
So the question is, why there is id and userId from database perspective? Why id cannot be utilized instead of userId?

**Comment by jmprathab** [comment]
> So the question is, why there is id and userId from database perspective? Why id cannot be utilized instead of userId?

@mslowiak, In general, it is a good practice to have a separate external ID(UUID) and an internal ID(DB id).

The idea behind having UUID as a user id is due to security reasons. For instance, if db id is exposed to user as a user id, it is easy to guess that a user id with a value of n-1 exists.

Another reason is to migrate to a database which does not have an ability to generate auto-incrementing Id.

Just a few random references:
* https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439
* https://medium.com/@Mareks_082/auto-increment-keys-vs-uuid-a74d81f7476a

Closing the issue as of now. Please feel free to reopen if required.
